"""commit message

Revision ID: 19a10cffe3b7
Revises: a374a9e45026
Create Date: 2024-06-13 20:59:16.770003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19a10cffe3b7'
down_revision: Union[str, None] = 'a374a9e45026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_entry', sa.Column('primary_id', sa.UUID(), nullable=False))
    op.alter_column('calendar_entry', 'symptom_name',
               existing_type=sa.VARCHAR(),
               nullable='False')
    op.alter_column('calendar_entry', 'symptom_value',
               existing_type=sa.VARCHAR(),
               nullable='False')
    op.alter_column('calendar_entry', 'symptom_unit',
               existing_type=sa.VARCHAR(),
               nullable='True')
    op.drop_constraint('calendar_entry_user_id_fkey', 'calendar_entry', type_='foreignkey')
    op.create_foreign_key(None, 'calendar_entry', 'primary_user', ['primary_id'], ['id'])
    op.drop_column('calendar_entry', 'user_id')
    op.add_column('history_of_illness', sa.Column('primary_id', sa.UUID(), nullable=False))
    op.drop_constraint('history_of_illness_user_id_fkey', 'history_of_illness', type_='foreignkey')
    op.create_foreign_key(None, 'history_of_illness', 'primary_user', ['primary_id'], ['id'])
    op.drop_column('history_of_illness', 'user_id')
    op.add_column('period_table', sa.Column('primary_id', sa.UUID(), nullable=False))
    op.drop_constraint('period_table_user_id_fkey', 'period_table', type_='foreignkey')
    op.create_foreign_key(None, 'period_table', 'primary_user', ['primary_id'], ['id'])
    op.drop_column('period_table', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('period_table', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'period_table', type_='foreignkey')
    op.create_foreign_key('period_table_user_id_fkey', 'period_table', 'primary_user', ['user_id'], ['id'])
    op.drop_column('period_table', 'primary_id')
    op.add_column('history_of_illness', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'history_of_illness', type_='foreignkey')
    op.create_foreign_key('history_of_illness_user_id_fkey', 'history_of_illness', 'primary_user', ['user_id'], ['id'])
    op.drop_column('history_of_illness', 'primary_id')
    op.add_column('calendar_entry', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'calendar_entry', type_='foreignkey')
    op.create_foreign_key('calendar_entry_user_id_fkey', 'calendar_entry', 'primary_user', ['user_id'], ['id'])
    op.alter_column('calendar_entry', 'symptom_unit',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('calendar_entry', 'symptom_value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('calendar_entry', 'symptom_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('calendar_entry', 'primary_id')
    # ### end Alembic commands ###
