"""commit message

Revision ID: 4462f23de8b8
Revises: 
Create Date: 2024-06-13 18:56:17.724707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4462f23de8b8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospital',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.Column('doctors', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('primary_user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('profession', sa.String(), nullable=True),
    sa.Column('hobby', sa.String(), nullable=True),
    sa.Column('super_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['super_id'], ['primary_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('calendar_entry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('symptom_name', sa.String(), nullable=False),
    sa.Column('symptom_value', sa.String(), nullable=False),
    sa.Column('symptom_unit', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['primary_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('history_of_illness',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('illness_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['primary_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('period_table',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['primary_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('secondary_user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('primary_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('relationship', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['primary_id'], ['primary_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('secondary_user')
    op.drop_table('period_table')
    op.drop_table('history_of_illness')
    op.drop_table('calendar_entry')
    op.drop_table('primary_user')
    op.drop_table('hospital')
    # ### end Alembic commands ###
