"""commit message

Revision ID: 8139079c3164
Revises: 08c6586c11bd
Create Date: 2024-06-13 20:31:05.964827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8139079c3164'
down_revision: Union[str, None] = '08c6586c11bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relationship',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('primary_id', sa.UUID(), nullable=False),
    sa.Column('secondary_id', sa.UUID(), nullable=False),
    sa.Column('relationship', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['primary_id'], ['primary_user.id'], ),
    sa.ForeignKeyConstraint(['secondary_id'], ['secondary_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('calendar_entry', 'symptom_name',
               existing_type=sa.VARCHAR(),
               nullable='False')
    op.alter_column('calendar_entry', 'symptom_value',
               existing_type=sa.VARCHAR(),
               nullable='False')
    op.alter_column('calendar_entry', 'symptom_unit',
               existing_type=sa.VARCHAR(),
               nullable='True')
    op.drop_constraint('secondary_user_primary_id_fkey', 'secondary_user', type_='foreignkey')
    op.drop_column('secondary_user', 'relationship')
    op.drop_column('secondary_user', 'primary_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('secondary_user', sa.Column('primary_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('secondary_user', sa.Column('relationship', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('secondary_user_primary_id_fkey', 'secondary_user', 'primary_user', ['primary_id'], ['id'])
    op.alter_column('calendar_entry', 'symptom_unit',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('calendar_entry', 'symptom_value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('calendar_entry', 'symptom_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('relationship')
    # ### end Alembic commands ###
