"""commit message

Revision ID: b5d70b7036d0
Revises: 19a10cffe3b7
Create Date: 2024-06-13 21:36:22.592133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5d70b7036d0'
down_revision: Union[str, None] = '19a10cffe3b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calendar_entry', 'symptom_name',
               existing_type=sa.VARCHAR(),
               nullable='False')
    op.alter_column('calendar_entry', 'symptom_value',
               existing_type=sa.VARCHAR(),
               nullable='False')
    op.alter_column('calendar_entry', 'symptom_unit',
               existing_type=sa.VARCHAR(),
               nullable='True')
    op.add_column('period_table', sa.Column('duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('period_table', 'duration')
    op.alter_column('calendar_entry', 'symptom_unit',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('calendar_entry', 'symptom_value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('calendar_entry', 'symptom_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
